name: Docker Image CI DEV

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag dev
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: covidgraph/motherlode
          username: ${{ secrets.DZD_DOCKER_USERNAME }}
          password: ${{ secrets.DZD_DOCKER_PASSWORD }}
          tags: "dev"
